### ISSUE TITLE
Unable to create a branch

### ISSUE THREAD

**Issue by RobertGemmaJr** [socrse/rse-groups#34]
Hello! I am attempting to add Brown University to this list of RSE groups. However, I can't seem to push to the repository on a new branch. I have the changes locally, here's the details:

```toml
[brown]
name = "Brown University"
head = "Paul Stey"
website = "https://ccv.brown.edu"
email = "support@ccv.brown.edu"
lat = 41.8268
lon = 71.4025
```
